# Generated by Django 4.2.8 on 2025-06-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BSCS-1A', 'BSCS-1A'), ('BSCS-1B', 'BSCS-1B'), ('BSCS-1C', 'BSCS-1C'), ('BSIT-1A', 'BSIT-1A'), ('BSIT-1B', 'BSIT-1B'), ('BSIT-1C', 'BSIT-1C'), ('BSIT-2A', 'BSIT-2A'), ('BSIT-2B', 'BSIT-2B'), ('BSIT-2C', 'BSIT-2C'), ('BSIT-3A', 'BSIT-3A'), ('BSIT-3B', 'BSIT-3B'), ('BSIT-3C', 'BSIT-3C'), ('BSIT-4A', 'BSIT-4A'), ('BSIT-4B', 'BSIT-4B'), ('BSIT-4C', 'BSIT-4C')], max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=55, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('student_number', models.CharField(max_length=55, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='crud.sections')),
                ('year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='crud.yearlevel')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=55)),
                ('course_lecturer', models.CharField(max_length=55)),
                ('complaint_details', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='complaint_evidence/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.admin')),
            ],
        ),
    ]
