# Generated by Django 4.2.8 on 2025-06-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=55, unique=True)),
                ('password', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('year_level', models.CharField(choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='', max_length=55)),
                ('class_section', models.CharField(max_length=55, null=True)),
                ('email', models.EmailField(max_length=55)),
                ('password', models.CharField(max_length=55)),
                ('student_number', models.CharField(max_length=55, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.users')),
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('student', 'Student-Related'), ('staff', 'Staff/Faculty-Related'), ('facilities', 'School Facilities'), ('admin', 'Administrative and Policy'), ('technology', 'Technology')], default='', max_length=55)),
                ('course_title', models.CharField(max_length=55)),
                ('course_lecturer', models.CharField(max_length=55)),
                ('complaint_details', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.admin')),
            ],
        ),
    ]
