# Generated by Django 4.2.8 on 2025-06-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='crud.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
