# Generated by Django 4.2.8 on 2025-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_evidence/'),
        ),
    ]
