# Generated by Django 4.2.8 on 2025-06-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_complaint_evidence_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='class_section_new',
            field=models.ForeignKey(
                'crud.Sections',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                to_field='id'
            ),
        ),
        migrations.RunSQL(
            # Create a default section
            "INSERT INTO crud_sections (name) VALUES ('BSIT-1A');",
            # No reverse SQL needed
            ""
        ),
        migrations.RunSQL(
            # Update existing users to use the default section
            "UPDATE crud_users SET class_section_new_id = 1;",
            # No reverse SQL needed
            ""
        ),
        migrations.RemoveField(
            model_name='users',
            name='class_section',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='class_section_new',
            new_name='class_section',
        ),
        migrations.AlterField(
            model_name='users',
            name='class_section',
            field=models.ForeignKey(
                'crud.Sections',
                on_delete=django.db.models.deletion.CASCADE,
                to_field='id'
            ),
        ),
    ]
