# Generated by Django 4.2.8 on 2025-06-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_sections_options_alter_users_options_and_more'),
        ('crud', '0008_update_models'),
    ]

    operations = [
    ]
