# Generated by Django 4.2.8 on 2025-06-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_merge_20250606_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='name',
            field=models.CharField(choices=[('BSCS-1A', 'BSCS-1A'), ('BSCS-1B', 'BSCS-1B'), ('BSCS-1C', 'BSCS-1C'), ('BSIT-1A', 'BSIT-1A'), ('BSIT-1B', 'BSIT-1B'), ('BSIT-1C', 'BSIT-1C'), ('BSIT-2A', 'BSIT-2A'), ('BSIT-2B', 'BSIT-2B'), ('BSIT-2C', 'BSIT-2C'), ('BSIT-3A', 'BSIT-3A'), ('BSIT-3B', 'BSIT-3B'), ('BSIT-3C', 'BSIT-3C'), ('BSIT-4A', 'BSIT-4A'), ('BSIT-4B', 'BSIT-4B'), ('BSIT-4C', 'BSIT-4C')], max_length=55, unique=True),
        ),
    ]
